[2020-01-04 19:04:49,447] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: my_dag.id_scrape 2019-01-05T03:10:00+00:00 [queued]>
[2020-01-04 19:04:49,495] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: my_dag.id_scrape 2019-01-05T03:10:00+00:00 [queued]>
[2020-01-04 19:04:49,495] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-01-04 19:04:49,496] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-01-04 19:04:49,496] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-01-04 19:04:49,537] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): id_scrape> on 2019-01-05T03:10:00+00:00
[2020-01-04 19:04:49,543] {standard_task_runner.py:52} INFO - Started process 26083 to run task
[2020-01-04 19:04:49,743] {logging_mixin.py:112} INFO - [2020-01-04 19:04:49,727] {dagbag.py:403} INFO - Filling up the DagBag from /home/stevo517/web-scraper/airflow-home/dags/my_dag.py
[2020-01-04 19:04:49,860] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: my_dag.id_scrape 2019-01-05T03:10:00+00:00 [running]> web-scrape-test
[2020-01-04 19:04:49,969] {python_operator.py:105} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=id_scrape
AIRFLOW_CTX_EXECUTION_DATE=2019-01-05T03:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-05T03:10:00+00:00
[2020-01-04 19:04:49,970] {taskinstance.py:1088} ERROR - 'function' object has no attribute 'Scrape'
Traceback (most recent call last):
  File "/home/stevo517/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 955, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/stevo517/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/stevo517/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "../scrape_for_dag.py", line 4, in scrape
    my_scrape = scrape.Scrape()
AttributeError: 'function' object has no attribute 'Scrape'
[2020-01-04 19:04:49,971] {taskinstance.py:1119} INFO - Marking task as FAILED.
